server:
  port: 8081
  
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value} 
  client:
    service-url:
      defaultZone: http://eurekatwo:5002/eureka


    

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://localhost:5432/cargotracker
    username: postgres
    password: 74875IM



  cloud:
    stream:
      bindings:
        cargoBookingChannel:
          destination: cargoBookings          
          binder: rabbit
        cargoRoutingChannel:
          destination: cargoRoutings         
          binder: rabbit
        cargoHandlingChannel:
          destination: cargoHandling
          group: cargoHandlingInBookingQueue
          binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
      