server:
  port: 5001

---

spring:
  profiles:
  - eurekatwo
server:
  port: 5002
eureka:   
  instance:
    hostname: eurekatwo   
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: http://eurekathree:5003/eureka, http://eurekafor:5004/eureka

---

server:
  port: 5003
spring: 
  profiles:
  - eurekathree
eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: http://eurekatwo:5002/eureka, http://eurekafor:5004/eureka
  instance:
    hostname: eurekathree
      
---

server:
  port: 5004
spring: 
  profiles:
  - eurekafor
eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: http://eurekatwo:5002/eureka, http://eurekathree:5003/eureka
  instance:
    hostname: eurekafor
      